version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:891377163278:task-definition/AppECS-app-cluster-was-service"
        LoadBalancerInfo:
          ContainerName: "was-container"
          ContainerPort: 8080
