version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "891377163278"  # AWS 계정 ID
    AWS_REGION: "ap-southeast-2"    # 프라이빗 ECR 리포지토리의 리전
    ECR_REPOSITORY: "min-repo-was"  # ECR 리포지토리 이름
    REPOSITORY_URI: "891377163278.dkr.ecr.ap-southeast-2.amazonaws.com/min-repo-was"  # 프라이빗 ECR URI
    APPLICATION_NAME: "AppECS-app-cluster-was-service"  # CodeDeploy 애플리케이션 이름
    DEPLOYMENT_GROUP_NAME: "DgpECS-app-cluster-was-service"  # CodeDeploy 배포 그룹 이름

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 23
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Preparing to build Docker image...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building the Docker image...
      - docker buildx build --platform linux/amd64 -t $REPOSITORY_URI:latest -f appDockerfile/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"was-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Starting deployment to CodeDeploy...
      - aws deploy create-deployment --application-name $APPLICATION_NAME --deployment-group-name $DEPLOYMENT_GROUP_NAME --revision revisionType=AppSpecContent,appSpecContent={\"content\":\"$(cat appspec.yml)\"}

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.gradle/**/*'
