#version: 0.2
#
#env:
#  variables:
#    AWS_ACCOUNT_ID: "891377163278"
#    AWS_REGION: "ap-southeast-2"
#    ECR_REPOSITORY: "min-repo-was"
#    REPOSITORY_URI: "891377163278.dkr.ecr.ap-southeast-2.amazonaws.com/min-repo-was"
#
#phases:
#  install:
#    runtime-versions:
#      java: corretto17
#      docker: 23
#    commands:
#      - echo "Installing dependencies..."
#
#  pre_build:
#    commands:
#      - echo "Logging in to Amazon ECR..."
#      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
#      - echo "Preparing to build Docker image..."
#      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#      - IMAGE_TAG=${COMMIT_HASH:=latest}
#
#  build:
#    commands:
#      - echo "Building the Docker image..."
#      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG -f appDockerfile/Dockerfile .
#      - docker push $REPOSITORY_URI:latest
#      - docker push $REPOSITORY_URI:$IMAGE_TAG
#
#  post_build:
#    commands:
#      - echo "Running deployment script..."
#      - chmod +x deploy.sh
#      - ./deploy.sh $REPOSITORY_URI $IMAGE_TAG
#
#artifacts:
#  files:
#    - imagedefinitions.json
#    - taskdef.json
#    - appspec-temp.yml
#
#cache:
#  paths:
#    - '/root/.gradle/**/*'
version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "891377163278"
    AWS_REGION: "ap-southeast-2"
    ECR_REPOSITORY: "min-repo-was"
    REPOSITORY_URI: "891377163278.dkr.ecr.ap-southeast-2.amazonaws.com/min-repo-was"

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 23
    commands:
      - echo "Installing dependencies..."
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Preparing to build Docker image..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Building the Docker image..."
      - docker buildx build --platform=linux/amd64 -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG -f appDockerfile/Dockerfile --push .

  post_build:
    commands:
      - echo "Running deployment script..."
      - chmod +x deploy.sh
      - ./deploy.sh $REPOSITORY_URI $IMAGE_TAG

artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec-temp.yml

cache:
  paths:
    - '/root/.gradle/**/*'
