version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "891377163278"  # AWS 계정 ID
    AWS_REGION: "ap-southeast-2"    # 프라이빗 ECR 리포지토리의 리전
    ECR_REPOSITORY: "min-repo-web"  # ECR 리포지토리 이름
    REPOSITORY_URI: "891377163278.dkr.ecr.ap-southeast-2.amazonaws.com/min-repo-web"  # 프라이빗 ECR URI

phases:
  install:
    runtime-versions:
      docker: 23
    commands:
      - echo Installing dependencies...
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Preparing to build Docker image...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building the Docker image...
      - docker buildx build --platform linux/amd64 -t $REPOSITORY_URI:latest -f appDockerfile/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - imagedefinitions.json
